# Generated by Django 5.2.5 on 2026-06-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('etype', models.SmallIntegerField(db_column='type')),
                ('nick', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pex_entity',
                'ordering': ['etype', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GPplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lastlogin', models.DateTimeField()),
                ('accruedblocks', models.IntegerField()),
                ('bonusblocks', models.IntegerField()),
                ('uuid', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'griefprevention_playerdata',
            },
        ),
        migrations.CreateModel(
            name='Inheritance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('itype', models.SmallIntegerField(db_column='type')),
                ('world', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pex_inheritance',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ptype', models.SmallIntegerField(db_column='type')),
                ('permission', models.TextField()),
                ('world', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'pex_permissions',
                'ordering': ['name', 'world'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('rpass', models.CharField(db_column='pass', max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'mc_ranks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mc_world',
            },
        ),
        migrations.CreateModel(
            name='SitePerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.CharField(choices=[('GriefPrevention', 'Grief Prevention'), ('Essentials', 'Essentials'), ('SimplePets', 'Simple Pets'), ('LuckPerms', 'Luck Perms'), ('ImageOnMap', 'Image On Map')], max_length=255)),
                ('perm', models.CharField(max_length=255)),
                ('bool', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=255)),
                ('comm', models.CharField(max_length=255)),
                ('descrip', models.CharField(max_length=255)),
                ('world', models.CharField(max_length=255)),
                ('altcomm', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('minrank', models.ForeignKey(db_column='minrank', default='10', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prankid', to='minecraft.rank')),
            ],
            options={
                'db_table': 'mc_plugperms',
                'ordering': ['-minrank', 'perm'],
            },
        ),
        migrations.CreateModel(
            name='SitePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passaduchy', models.CharField(max_length=255)),
                ('mailaddy', models.EmailField(max_length=254)),
                ('player', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('dateadded', models.DateTimeField()),
                ('rank', models.ForeignKey(db_column='rank', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rankid', to='minecraft.rank')),
                ('uuid', models.ForeignKey(db_column='uuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='gp', to='minecraft.gpplayer', to_field='name')),
            ],
            options={
                'db_table': 'mc_players',
                'ordering': ['rank'],
            },
        ),
    ]
