# Generated by Django 5.2.5 on 2026-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_auto_20250402_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
