# Generated by Django 5.2.5 on 2026-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seotitle', models.CharField(max_length=50, unique=True)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/')),
                ('body', models.TextField()),
            ],
            options={
                'unique_together': {('pub_date', 'seotitle')},
            },
        ),
    ]
